#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'qr-reader','console_scripts','pose_estimate'
__requires__ = 'qr-reader'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('qr-reader', 'console_scripts', 'pose_estimate')()
    )
