#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'range-sensors','console_scripts','sensor_filter'
__requires__ = 'range-sensors'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('range-sensors', 'console_scripts', 'sensor_filter')()
    )
